// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAC2yoMGz2SrRIGrvtMrb-jaBDTTCUETNI",
    authDomain: "flutter-facebook-4c58a.firebaseapp.com",
    projectId: "flutter-facebook-4c58a",
    storageBucket: "flutter-facebook-4c58a.appspot.com",
    messagingSenderId: "957475916382",
    appId: "1:957475916382:web:8aede757d4736a6e80c2cf",
    measurementId: "G-TLKZZM2KR6"

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIpdiKyxPScWUfFmJJncT-cpkaFRCeDKE',
    appId: '1:76792423265:android:2f5f96b6610edc28531b20',
    messagingSenderId: '76792423265',
    projectId: 'isp-test-a441c',
    storageBucket: 'isp-test-a441c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv1ZC9fHX2hDQjTREb3nneGSGB3P32mvw',
    appId: '1:76792423265:ios:a5f281ba0735cea1531b20',
    messagingSenderId: '76792423265',
    projectId: 'isp-test-a441c',
    storageBucket: 'isp-test-a441c.appspot.com',
    iosClientId: '76792423265-f2526vtrhqa83t61t8hdp48p333qvtoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv1ZC9fHX2hDQjTREb3nneGSGB3P32mvw',
    appId: '1:76792423265:ios:a5f281ba0735cea1531b20',
    messagingSenderId: '76792423265',
    projectId: 'isp-test-a441c',
    storageBucket: 'isp-test-a441c.appspot.com',
    iosClientId: '76792423265-f2526vtrhqa83t61t8hdp48p333qvtoe.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicApp',
  );
}
